---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: immich-secret-values
  namespace: immich
spec:
  encryptedData:
    values.yaml: AgCRXIj52nixsEnQwWQdiNK7xyrH+EO4iaJ/8WKXc9ayLpaOwNDLffILBCaLcN9NLPCMx4SK67/i83xSRLi04UxAsVCPJ5T7qlLHGed5p0BHzx8uUgpWs5Xe/nfq4uMjZP6tg+aTlknHwf2COSdt+NhCQxPwGAI9GPQYgIvyN8tLHqIoI90CvytbwXk0V3Thz3Wg/YO8eqVKUvZaaN1cLt68vT8buZxiVdQoTNyosCmQ4Lnp8f46ypsibl8pOOkS5qAz+1h+dqU3OZJToPJuQ6/opImRpf8QuEwKQqG7YDP9MtuXjZQCTxLPsAImbuYJBZxdFbpeGOaeUHY8Pci92tgaws4s+0F5ahSL83NJIqIaXxfRiXBqVgsFbkfh6LN6tuwSDfU90N8i2jFAtBjQG7r7PgOPEa/jf+E+XAvERPowy4oJMBYHJ0eKOM6UEa0prFCZloEviLnDdYsqZ8i1RrCEnCykGkwyKK4dK69Gx43XYe4J4zPEUKaN8o9K+rPvLWyM8uu8EoAbtuDHmumUXNJhL4nzxaAcEX0VBtc2ObPKCDse9ryeI9glQBrjgr2e7aZpFy5QrIVHfAmiLiTrWz1C7z+ibGiqa1B2xVFn7bEaED4uTNToQK5esW92qhUkfGZJky6ErHgM1+dYDL/M6QMXq88osFlaoAEEwNS2tISjQ41j6c83uUhlgY2iHmS0e7trcSZUmvdFA0RDTuw0kMRpxh0Iu4cuSlpJ0muag1SFjNpGzHlvsRvMca6/EvJBPILUdXzI8Q/kNTqKsSmSe6Juwa0FZjKBtI8UvMJc8TECJ1F1oqGMZ6MEYwubDZacGXCflugvJa+hKto3Y9WYa8lJuMHIcjuFMqeD4A7YWWqQ+TeJdgHBTN1pKRMkDCICx1fuT/V8G5WpDqOHg30gva4AUtS6YwMsB0rWsEoxijjJFQIXQRs0/tZ3x5nZ7J7NmHSBE880CVHDU1e4oGzV46/Kmtp4AWL32TitIij66EVB1TpSO337sOarXKfwld2AL3qhUgaLrE1KP+X6vVif0n1PRMoboPiaLx/6iWpyEFBQrBwRiHrJ7i3LwFrHyLpDnxAZHXiuVatWEg6A0qwI3ZkZa4uRNLfuY6dsii2Lr/Q3SRJIPLFwtIUEm1+m8q3LvxS2wV3RUyy4FJgv/6lCGMV46NIMFSRk0KOqc9JJ7Z6jtucYLKVv/s8yfSb37bZPfkViBjIGUs44RSPxRSxOwtQaPWTiaA4=
  template:
    metadata:
      creationTimestamp: null
      name: immich-secret-values
      namespace: immich
