---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: k8s-monitoring
resources:
  - ./k8s-monitoring-namespace.yaml
  - ./k8s-monitoring-helm-release.yaml
configMapGenerator:
  - name: k8s-monitoring-values
    files:
      - values.yaml=k8s-monitoring-values.yaml
configurations:
  - kustomizeconfig.yaml
