---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oncall
resources:
  - ./oncall-namespace.yaml
  - ./oncall-certificate.yaml
  - ./oncall-traefik-middleware.yaml
  - ./sealed-oncall-credentials.yaml
  - ./oncall-helm-release.yaml
configMapGenerator:
  - name: oncall-values
    files:
      - values.yaml=oncall-values.yaml
configurations:
  - kustomizeconfig.yaml
