---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vm-metrics
resources:
  - ./vm-metrics-namespace.yaml
  - ./vm-metrics-helm-release.yaml
configMapGenerator:
  - name: vm-metrics-values
    files:
      - values.yaml=vm-metrics-values.yaml
configurations:
  - kustomizeconfig.yaml
