---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./immich/kustomization.yaml
  - ./karakeep/kustomization.yaml
  - ./ollama/kustomization.yaml
  - ./n8n/kustomization.yaml
  # - ./rsshub/kustomization.yaml
  - ./wakapi/kustomization.yaml
