---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./homepage/kustomization.yaml
  - ./immich/kustomization.yaml
  - ./karakeep/kustomization.yaml
  - ./wakapi/kustomization.yaml
