---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo
resources:
  - ./podinfo-namespace.yaml
  - ./podinfo-helm-release.yaml
  - ./podinfo-certificate.yaml
