---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: invidious-secret-values
  namespace: invidious
spec:
  encryptedData:
    values.yaml: AgCO2Qk3GIpv+lVRAqBlksPc2HyYIphoy/u1HFRIscZO9WCDZN6xgT2wO9nKfHMFQWbDypT0eyxM6YH+n1nj08oiIf+tjWcKC7lPhRj9NOOH6GR5D/OeJFKnXgNZuvSMmHi0OgCWsxpjIs+0tg7FTKtJigd0GF3hQRYCSFomblNMsFA7LpHiAcPOceRx8yRi6fRh4Xae41Kmr45kwDpuZP6bev+a6XNpcodadkwiJQuQJtahZwGe+ngyKgKTC23H5sGgKW+/JyizTMG6KOPszkMXnvjYI/cfA8xoYtuV1UON3t3sSbfZv6mamKMpTR0v6E9VauTBbGmQz/1aKRDB/ERUTY1q6VfUEq23Cf/ZVmuwqPrLKNhx9LxcvRTs4qqWHE6R45qRPwvG9N6+nEBV5pPDDa59YP2E46Fg3vIKDM2jytEg8qOTCWRAUgjakMKnOm2pdMjBmS+04VDct8pe+7PSqKg1f1IOdAj5B/qswkTkfFL5lHY/bhRXae9Rd6YW99YAXwtUcJ7tYGkdRvQaZquXsaxNzLwqwEZ5XAYv8+TUs2YXQnmFP/4lQt352omoWr/v1eBybvVVA0spyJgMet5UUzsWqtAV7ePeY1q9wUaupMLeafT/9t2FBQ6hXfBSBV4du6GietnoWGrS+ByYbTs/+tittS87qBKMFiFzdh0yLnR6u5DaX8Duf6KzPm3NhBWi0JioSqTgKLaNU/RlkqPuCzs1gqDntuT5wmEvogrGc7w/mC7kWn1t70rVXeXwjFMalD/+GIigwA2qgUwT1otmZlgNVFlg8RSxrZr+QZ9wriZE5jilLmTswp8zWqq8IgV1xRTDqNvSCPOUQ9saP2/ruCfJB0EU+lGzYO0PQOMCz7p19dEfEiEoun86VLF7fC8ItQ44mMoUzgBzl4FsPZ1qzYZ1elVJBeYNpjOOEpWO9c03gRami9AMp3P0aBhbS1bCbhqLaJB6XczkwcSfVrN3oo5w7Yhl2FBWzkmWk1PgFe4ywzHNzm0Cmu5tN2iA5RoRoXM+nu9RFh8NSp2zqm+Io5ZSsI2J14FURrhc5bnHzxcu9ov3H6D8rnKnPxEradpECVTESnrx3dn7Kpr1PaPkO+iDX21AmjLQA9lD91W0RIIwdhmwovjOzkCABwlxsIGIG94+Sq/J2ecLRKZxgpp1hWQMmcE9Xv40vRv1UvJdnxRPeEPeTVQNG8V0C/Mg9rX/8vNTCWb62SGYxwjiCZWHY6LQNCnwpFqURbzCpCzzLDtVqWqprNIQyIhr5fL9R6S3cfRZdm/hqVoW0aUta+hekyrzuE8MevRvKZ9b3xPcmmrv
  template:
    metadata:
      creationTimestamp: null
      name: invidious-secret-values
      namespace: invidious
