---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./vm-logs/kustomization.yaml
  - ./vm-metrics/kustomization.yaml
  # - ./grafana/kustomization.yaml
  # - ./k8s-monitoring//kustomization.yaml
  # - ./loki/kustomization.yaml
  # - ./mimir/kustomization.yaml
  # - ./oncall//kustomization.yaml
  # - ./tempo//kustomization.yaml
