---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./grafana/kustomization.yaml
  # - ./k8s-monitoring//kustomization.yaml
  - ./loki/kustomization.yaml
  - ./mimir/kustomization.yaml
  # - ./oncall//kustomization.yaml
  # - ./tempo//kustomization.yaml
