---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./tempo/kustomization.yaml
  # - ./gatus/kustomization.yaml
  # - ./goldilocks/kustomization.yaml
  - ./grafana/kustomization.yaml
  - ./node-problem-detector/kustomization.yaml
  - ./ntfy/kustomization.yaml
  - ./otel-collector/kustomization.yaml
  # - ./trivy-operator/kustomization.yaml
  # - ./signoz/kustomization.yaml
  - ./uptime-kuma/kustomization.yaml
  - ./vm-k8s-stack/kustomization.yaml
  - ./vm-logs/kustomization.yaml
