---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./aqua.yaml
  - ./authentik.yaml
  - ./bitnami.yaml
  - ./cilium.yaml
  - ./cloudnative-pg.yaml
  - ./coredns.yaml
  - ./deliveryhero.yaml
  - ./democratic-csi.yaml
  - ./fairwinds.yaml
  - ./gatus.yaml
  - ./grafana.yaml
  - ./jetstack.yaml
  - ./kube-vip.yaml
  - ./opentelemetry.yaml
  - ./podinfo.yaml
  - ./reloader.yaml
  - ./sealed-secrets.yaml
  - ./snapshot-controller.yaml
  - ./traefik.yaml
  - ./uptime-kuma.yaml
  - ./victoria-metrics.yaml
