---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
resources:
  - namespace.yaml
  - sealed-democratic-csi-secrets.yaml
  - democratic-csi-helm-repository.yaml
  - democratic-csi-helm-release-iscsi.yaml
  - democratic-csi-helm-release-nfs.yaml
configMapGenerator:
  - name: democratic-csi-iscsi-values
    files:
      - values.yaml=truenas-api-iscsi-values.yaml
  - name: democratic-csi-nfs-values
    files:
      - values.yaml=truenas-api-nfs-values.yaml
configurations:
  - kustomizeconfig.yaml
