---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: uptime-kuma-secret-values
  namespace: uptime-kuma
spec:
  encryptedData:
    values.yaml: AgAycsvzVuJW3cDQ9LHFUSsprFzmhahAKKgNwTYwKANg1bpzEP8nR5EM6/hZWTIPcxwOlpt+/OkEV5iumWc9JbozVJ1PPn6w60PA4lDatBTJx9JDae3l44vPyxa0xQ6uARy68itDnvLEVOie4CiJctBAdxqNrbzwodcDXzBhwbqU7VBxF5CqEPPYr+Ye6QA0JMCibSQmXyhYq8Ll5SDVq3+huqDkZ6enp6mLAeqYelrJjokaR4v525tlMu3u/LJh40tCSDbJxQebUg/j1dNh4UDlzg+z++8UKJwTsZptkypTNRlPxMwPFYRy0EfgZBNduSJODb2/jl6keU2xPaK3C2LIUPLcWJ6PBzeAzDabr9qXbSGuwhKHz+aRnyM1xxpHeJ6ZrAb1BnP2+q9n3ibGRGGIZTM4hDV8W/OygS3o2aMRdDlWfh6c1AoA6yOA1UcpdlQZZ4WRgHV2D1pKuESfLUvoff5wMVlnDpWnSGJ23DMq81E2BO9PO52cGBJ76nltwd0A7vZ00sG0jctGcZar1VYVKrYdIRJ8AxaeAebFe2eqMzu3Rn+6eYGVElTa5PAdsrB4Vzz7rvz9PwrtUb0MJenWXqONOjTJCcdn4RCEMXss2XLKdo+edvrcyS/TzXxu1selbxrvEzfFOQcen9Q/KImLizxo8Ze4IC/l0EJWATrD0fWvsOPtvf+JkbkTxN2wHFyIQcJQkL7XFUWatcazFvxTVE9uYf6o5bNQlsO9laJ7nc1TPYN4EP4Q1yL3EcXLfXhaeDVrqJ+gYut8/ZoZyUuWU4JGnmAJe+vTQ74saxy0WHFylLhkIN3mBXdEzIvC+dUUFNwEdOuHXGpIcnX2f7bkQZnFNYI6bHSzYXjHiO2JNKVJnq3IgqEjFORnEPLiJ7cmsp9ax5bHPnp0S9um8Rqf+H/K8UYOKEQLvNJyIluipZQjHT7dVzST8YHH6ppOEpdSyI1uZUfbKOHT29+w4fQ=
  template:
    metadata:
      creationTimestamp: null
      name: uptime-kuma-secret-values
      namespace: uptime-kuma
