---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-credentials
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgAkZdfhiLgG6MqJfzgdWbTtzfmdhFfU8kKQRldj5xKA+165mcwssEyHWfpl2Gyuju6oQRu22e1vnxB4DBZgXtq9LSXvpfQyuS2KyKHdXEht9/gsHZPx+mhmCrCENKgUWUIxn/2icvXb41xvXC+4Th6xYkzVyKTSd1ZBl5n1GFg/laB+NxokeURdW/g3O1zpjeCWCkAfFFccIBtBGcgn0hXrOzxIXdgkL0Gv1BhRgO13kI8upmCx8OTzMrz3bwaUzgMbDDlDW7Up1EEvJAMxK4KihhoJrJQUEutTnRBnnXD1qWRIDwxRN8X59z6p95H0pfp795Ul3fCcxENJiNB/9BDJMj5abqpkG6mYajKqFHOJeQlsGpiE2k6FToBb/bD6PiWBZbdEsnQexMk/4uSVrbI/p6/bHYdYX7lJl+XWDDICjaa2VKuK8nccmEmxiVEQECq5FatOhPRSyAp9LU1ZwRibG/eQXhcsNFowo30HH/9bxGagShB5QcBweIl22V61VupTV7cJJ/YaECf3/klLLPhQHuW5vVwNiwbkSLXL23RLVkd7VAXlVVPQOIMhWJyGm9ttVzMkYTzD3WHp/GQN36RjLDBktUXWc+gf4e99p01FOvD3/4VZe2QmhezOfXuH5xDFc+jhKJQNwsFP6RSZFlD6oNc88ao4fz+Gv021PlT5M9TPfTp+lY6H9pas7dYzjxDIp+bDIZUTWJ1dBacOahbbd6IAjQ== #pragma: allowlist secret
    admin-user: AgB8AroXODZS8LOVjJ5y+rKaOv4BvY3sANeJn5qN+6m5/ztil4cElAgJO89hQfykqFYQ9rOcwlA4bWO9US3pzxx4xw7wGCOZ/6lUiTomjOEsYdIi0VPkvYgbD4GKZWw4mz5OmAKo1txYiMoxilPAUOQAWg6rMT0iCXHIivjRr794TohAmmMgV/MNPaqcyBd90VTrNeFlZ5eTTNrbBMuHri/212j0pnVRBZrQrpLfMww1wowPgq3hSUP30BsGFkNBPyzGd6RzB/wJzAKgekSg4uxHJYdXbLvC4bm8ezPu8XEmvEkUQr4zma+mm5IYgflilWd4Od6kTl1suE1dMmoF7iS0lZk7+CIUZe9Rl/mBkPHLhaug1E3l2MLtMIEepoh7OLNcnRv9QF/RBTjgsR1vtTt6XFk/iu9vQxezs7fv/b87En2mUBhPAnSKaujL917KrqhQIsQiWIh69J5O0e+CPzFPZLVc3hPRb9hvg86h7MnjvzfhOJDrl05j0epn86AYtdD7FV0A6Lxy4ruqYwZh9gE9cmXQKG0oGtkp7ZnpfqEzvOoTmyIszXFSfHjRmyedKc1GPhsI+zuO1ngJvM3l514Td3TLvOcyPt9TI8FYWm/h6SGFCqlsQWvKXutqwaxl4KdXXIs6dTk+StMHvpg8fTpWsrZPtGvUQnbN6UKQVB9kEmqru1R/UswJx+MVVQnS600T3V7PdQ== #pragma: allowlist secret
  template:
    metadata:
      creationTimestamp: null
      name: grafana-credentials
      namespace: grafana
    type: Opaque
