---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-credentials
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgBoTSAw8Hb5evlZDwfD0GyX3DSHGkFk+ugXRF55icsh6l7Srtwp4Qo0ZW3G/LghXeyp8XmGa1Kp3MIKTqvylvc+M+wLMHggUspjGZ0n2tgFk3skW5IAdlqvYcLk1bJVkeYfEMCfNMmV+SoCCI2UwKV2LowbrzdNR+efcc8VJ5W1UtPDyp29p7i78bgjT8HxR9pNTzPjMmdcluMFjrdJO3xKzjaeVz2dnoS8Bj5Wwb6VUHXlmjn/HZJ8aXNTfdLFVAl4MQJ33vjAX5cGnZIxWGUnpkUUFUkKn+dMopGHBLJPGDkBDGLXQNV1jFZshQRZ0JVykKnyLY1Mxo1NwnmXqt9r64CAVu1cIhEoUwHGHtjZR0m45RY0/nB4Ko2V2JdTnXf/hBJyRVQuIes/MFESdnvEu2dk9+Frt4LC8WPhFKxwPg82eGgDLhUrCqJQ/5h0vEzNVkPYB6jIpWuGqJo0vaEf4iu6feFE+BndYIBLiOgFHUpl0mATSMwOSZvv0T5Mv45t+WaTnRnnIQ3Rw4GGMjzjPiTj0at5P1d3bCaHKVxj6FuWsFcD6UjCk30zRN6q+oBOdAgksyEFtVL/qQjpBfJQLFIefR2oAnVeoa5Wxn4niizojgvNh/w9P8IXmYtB87OnSur2MpwFCL6AJhjVHywtcUNdPZ+7om4lNr65XFUXNQNbE2s6ZBI9Gu8bc461vkzgnRtW4OkuawyFAn1Ishum5p1FrA==
    admin-user: AgAswGRILuYgrQfTChmweCLC4IiFKO6TVfWBkjuJhGwvF9yMowvi02hcryAY0klVsAtLdv1w245W8zrzr3FoX1HN7JNREIvmdqVGALx5dMZRfm3VvOUwijopjE9CaP6Tsu34fjX+atUTu1NcP5yS+RUaE2ljeE04HmX0emogHmz6gfaN899GJO4C9bnjMQm2xh4Eu2impEzuSZy9biM1LYMXqNIE7PGJdFS+XjEH6Z1qkdM3Cm8heqHZunfvuqX1a9rBmAvyN8+ZNRlTdv+Y3z5pXV8OhAL3I27ye+DL8pnrs1YghPlqlCnzXhxKW12QwI9ayGe+rNMtVq3LnEnD8Xey7hJYel8xmT22XuerFum8XR7C+Aslel6fIP9tCxIdU+gU/zK9lFWQdM5olvBqc4PCLxBGr8JoDUxmEBTkwHlkKmogXZqI9RjnpTia5uR+ycBjOCdBYWh6VECO1TVhHVVvs1N+ZPat2sdKCIKWOFDT4D1G/d7UpzNxjdRHJ881DA1bRznrmYbc2LhIJL9FouwHE4DxjNm47AY4YaS69SZHjXrDmb+bjS9g/KicKzOD/C9ijWqPpQdO6/VtgzN21lFBgZrFcjugXlxWbxORbZrFsXa7ON+skvzfoKYPhqtphwUAn0DbTt8ALVuD+VYrpoPu5ZNIFk84ynoL6WnosL7tiqSJ2XFPF7Lj56VsgQ3+LyS2BTO+tA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-credentials
      namespace: grafana
    type: Opaque
