---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-credentials
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgAxaPR4w2mcYM6JoLVMPgYxiPXXPWXLPhvYdepX0OJM9zjJDZFAVHFfFld80hDMMa194MnJUM14tmQYsRZXIEcFl/cOrv5VZ8za1SJxrafL/KQdckoupK5EzBad7jL2FgzEyJiriuvEnbY0ZE2ecFeJmbSyg/3SpR70wrlQUUEpruybe43CodkF941gT8S7anjFCQxnr/LId1r2vPxVpinSaC/dw+F6S+56DO0dohBZEpojSYqqQLOUTll0R9ZHyCXtio18LuAXzoyIEyKu5LN6TMQjk46Zn5anPeZ54q9l5r7GMsfaBprDYK9j6EVgwDVFKcvCAWZZO0qJN/PhJ550bdc8LcPaYlofXwSalagsF5YnaPnYVdxkArOmJ6oVThWRkIg/6lqJyHq85eQfRb50hA7WxbYzEz2DNKiRNKRNwSCnSCNEXGVbGPx6hY/oBc2qF8KjVzNtQznjr7uIs3qjxBoYMGshXE6ffIsGckDZW5Z1m8+hlVyzfjWr8fKjGvsKSOjB/M+qH5f8T2ztQAWekTWO4295LujirRml03RH+XoFTMyzTnczNA45VLsTOoCFDGzQm7fzrLJvIAIVffB/Uw4nXOaPqwxpjTrOpPBDbbjgxzCnocqthyi3aCgTRd+Gg3qOuZqs2hxgBsmoNOq2FTeL5qLH2pY/3mXKUQw0y/Zl2x3aJFuaXykUebQBl/bq+zqDI8RYFQ33ojV7d9yTqBH88w==
    admin-user: AgCYy9U/f6eKnlsGU+QQnGDbhoedq4JNMTKYWNyrqst7Ed8E4/PmweyCzC7iPXgOlmsZ87kIv46kt9wnWiUEe4AJa/u6NGWYr5U7EbGsU//KTZDsUE2oiqLdDyHXpwGNrVZ8fMnbyvOzfcy2uteFjjOcF+3zYVcW1DQTlFirC0hxj/yYz5ZqUDzKYteahb4rwfZhbpIpnlKhAlT7wCOirE5yyZTdUBmGZ9bCxdXQoMjUIjWUOtUqbKTM5cxmyWyaeGfVELZF9WRzL62/l8cBXz3c07py1iIZ90sVuaWNFw1Iqt6vj+kvmZlEnEl3h7UhoQ3Z8yAaiALEEUJhVdWl4KXzQu5vNxM7CD8/Hvd+I280GjXphX0lObLPO2j9fklLbi/1vy+yVcs3zRV8WFcMHXJ8uopJdRWg21uLumiMk7cg/CI/CCQwpxq2tf9z7d7/MrfB0oKyZmKRaPQAVaaflRzsLHC3BsELLcln+Q3MRZmetZQf9xIewlhN0Y97IdgHrVWGZI7Y0+G5+6RD6udVveUZsFB9vD5kikMLnjrGs94z2E3JLJAUysenFh7bR+gjaRL5j/Wnpkte+9l+HCG/l1Xd3zLmAeObdCIsj/RYWwpXf31mmg2NXWOGEbbdnt4pisZhq3lk8+exp0lClnYJsXBZ8nB00K3fZPN+nGjPNDZgPEdbrJBg33JXt4BfnSMVzW7pa1+KlA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-credentials
      namespace: grafana
    type: Opaque
