# https://kubernetes.io/docs/concepts/configuration/configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  name: victoria-metrics-logs-datasource
  labels:
    grafana_datasource: enabled
data:
  victoria-metrics-log-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: VictoriaLogs
        type: victorialogs-datasource
        access: proxy
        url: http://vm-logs-victoria-logs-single-server.vm-logs.svc.cluster.local:9428
        isDefault: true
