# https://kubernetes.io/docs/concepts/configuration/configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  name: victoria-metrics-datasource
  labels:
    grafana_datasource: enabled
data:
  victoria-metrics-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: VictoriaMetrics
        type: victoriametrics-datasource
        access: proxy
        url: http://vm-metrics.vm-metrics.svc.cluster.local:8428
        isDefault: true
