---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: whoami
resources:
  - ./whoami-namespace.yaml
  - ./whoami-deployment.yaml
  - ./whoami-service.yaml
  - ./whoami-certificate.yaml
  - ./whoami-traefik-middleware.yaml
  - ./whoami-ingress.yaml
