---
services:
  hbbs:
    container_name: rustdesk-rendezvous_server
    user: 1023:1023
    image: rustdesk/rustdesk-server
    command: hbbs
    volumes:
      - /mnt/2000/container-mounts/rustdesk/data:/root
      - ./healthcheck:/healthcheck
    network_mode: service:ts
    depends_on:
      hbbr:
        condition: service_healthy
    restart: no
    healthcheck:
      test: ["CMD", "/healthcheck/checkForHbbsProcess"]
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
  hbbr:
    container_name: rustdesk-relay_server
    user: 1023:1023
    image: rustdesk/rustdesk-server
    command: hbbr
    volumes:
      - /mnt/2000/container-mounts/rustdesk/data:/root
      - ./healthcheck:/healthcheck
    network_mode: service:ts
    restart: no
    depends_on:
      ts:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/healthcheck/checkForHbbrProcess"]
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
  ts:
    container_name: rustdesk-ts
    user: 1023:1023
    image: tailscale/tailscale
    env_file: tailscale.env
    environment:
      - TS_HOSTNAME=rustdesk
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_ENABLE_HEALTH_CHECK=true
      - TS_LOCAL_ADDR_PORT=127.0.0.1:9002
    volumes:
      - ./tailscale-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    # https://github.com/tailscale/tailscale/issues/12758#issuecomment-2564770640
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:9002/healthz"]
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
    restart: always
# Because using docker host mode
# Just in case you forgot the ports:
# 21114 TCP for web console, only available in Pro version
# 21115 TCP for NAT type test
# 21116 TCP TCP hole punching
# 21116 UDP heartbeat/ID server
# 21117 TCP relay
# 21118/21119 TCP for web socket if you want to run web client
