---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mimir
resources:
  - ./mimir-namespace.yaml
  - ./sealed-minio-credentials.yaml
  - ./mimir-helm-release.yaml
configMapGenerator:
  - name: mimir-values
    files:
      - values.yaml=mimir-values.yaml
configurations:
  - kustomizeconfig.yaml
